### ISSUE TITLE
Question about the image size

### ISSUE THREAD

**Issue by pink-red** [SmilingWolf/JAX-CV#13]
Hello! Following #12, I've noticed that you've corrected the image size from 448 to 512. That got me curious: why is the size different the one in configs of the models on Hugging Face?

By the way, thanks for creating this amazing project!

**Comment by SmilingWolf** [comment]
The images are randomly cropped (only a little bit, don't want to risk cutting away too much) and resized using random algorithms during training as part of the augmentation pipeline, to make the models more resilient to shifting, zooming and the particular choice of resizing software during inference.

Saving the images slightly bigger than the target size makes it so that the cropping and resizing augmentations don't end up being no-ops.

**Comment by pink-red** [comment]
Ah, I see, thanks!
